export const apiURL = {
    user_auth: '/api/authy',
    input_validate: '/input/validate',
    mpm_verification: '/mpm/verification',
    mpm_verification_v2: '/mpm/v2/verification',
    mpm_verification_data: '/mpm/verification/data',
    report: '/report',
    report_v2: '/v2/report',
    report_v3: '/v3/report',
    report_v3_polling: '/v3/report/polling',
    config_table: '/db/config_table',
    list_configs: '/db/list-configs',
    list_jobs: '/db/list-mpm_jobs',
    mpm_jobs: '/db/mpm_jobs',
    timescale_time_range: '/timescale/time-range',
    timescale: '/timescale',
}